# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Pedro/Dropbox/UA/CR/Project/CR-Project/SquareRootCop/SquareRootCop.srcs/sources_1/bd/mb_design/ip/mb_design_auto_pc_9/mb_design_auto_pc_9.xci
# IP: The module: 'mb_design_auto_pc_9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Pedro/Dropbox/UA/CR/Project/CR-Project/SquareRootCop/SquareRootCop.srcs/sources_1/bd/mb_design/ip/mb_design_auto_pc_9/mb_design_auto_pc_9_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_design_auto_pc_9'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Pedro/Dropbox/UA/CR/Project/CR-Project/SquareRootCop/SquareRootCop.srcs/sources_1/bd/mb_design/ip/mb_design_auto_pc_9/mb_design_auto_pc_9.xci
# IP: The module: 'mb_design_auto_pc_9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Pedro/Dropbox/UA/CR/Project/CR-Project/SquareRootCop/SquareRootCop.srcs/sources_1/bd/mb_design/ip/mb_design_auto_pc_9/mb_design_auto_pc_9_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_design_auto_pc_9'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
