# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Pedro/Dropbox/UA/CR/Project/CR-Project/SquareRootCop/SquareRootCop.srcs/sources_1/bd/mb_design/ip/mb_design_axi_dma_1_0/mb_design_axi_dma_1_0.xci
# IP: The module: 'mb_design_axi_dma_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Pedro/Dropbox/UA/CR/Project/CR-Project/SquareRootCop/SquareRootCop.srcs/sources_1/bd/mb_design/ip/mb_design_axi_dma_1_0/mb_design_axi_dma_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_design_axi_dma_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Pedro/Dropbox/UA/CR/Project/CR-Project/SquareRootCop/SquareRootCop.srcs/sources_1/bd/mb_design/ip/mb_design_axi_dma_1_0/mb_design_axi_dma_1_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_design_axi_dma_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Pedro/Dropbox/UA/CR/Project/CR-Project/SquareRootCop/SquareRootCop.srcs/sources_1/bd/mb_design/ip/mb_design_axi_dma_1_0/mb_design_axi_dma_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_design_axi_dma_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Pedro/Dropbox/UA/CR/Project/CR-Project/SquareRootCop/SquareRootCop.srcs/sources_1/bd/mb_design/ip/mb_design_axi_dma_1_0/mb_design_axi_dma_1_0.xci
# IP: The module: 'mb_design_axi_dma_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Pedro/Dropbox/UA/CR/Project/CR-Project/SquareRootCop/SquareRootCop.srcs/sources_1/bd/mb_design/ip/mb_design_axi_dma_1_0/mb_design_axi_dma_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_design_axi_dma_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Pedro/Dropbox/UA/CR/Project/CR-Project/SquareRootCop/SquareRootCop.srcs/sources_1/bd/mb_design/ip/mb_design_axi_dma_1_0/mb_design_axi_dma_1_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_design_axi_dma_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Pedro/Dropbox/UA/CR/Project/CR-Project/SquareRootCop/SquareRootCop.srcs/sources_1/bd/mb_design/ip/mb_design_axi_dma_1_0/mb_design_axi_dma_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_design_axi_dma_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
